kind: pipeline
type: kubernetes
name: default

steps:
  - name: terraform
    image: hashicorp/terraform
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - echo "$AWS_ACCESS_KEY_ID"
      - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#      - echo "Printing environment variables...."
       - terraform init
#     - terraform plan
    when:
      event:
        - push
        - pull_request


