kind: pipeline
type: kubernetes
name: default

steps:
  - name: terraform
    image: hashicorp/terraform
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_SECRET_ACCESS_KEY
    commands:
      - echo "Printing environment variables..."
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - terraform init
      - terraform plan
    when:
      event:
        - push
        - pull_request


#---

#kind: pipeline
#type: kubernetes
#name: default

#steps:
#  - name: terraform
#    image: hashicorp/terraform
#    environment:
#      AWS_ACCESS_KEY_ID:
#        from_secret: AWS_ACCESS_KEY_ID
#      AWS_SECRET_ACCESS_KEY:
#        from_secret: AWS_SECRET_ACCESS_KEY
#    commands:
#      - terraform init
#      - terraform plan
#      - terraform apply
#    when:
#      event:
#        - push
#        - pull_request
