kind: pipeline
type: kubernetes
name: default

steps:
  - name: terraform
    image: hashicorp/terraform
    environment:
       ACCESS_KEY_ID:
        from_secret: aws-access-key-id
       SECRET_ACCESS_KEY:
        from_secret: aws-secret-access-key
    commands:
      - echo "Printing environment variables..."
      - echo $ACCESS_KEY_ID
      - echo $SECRET_ACCESS_KEY
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
    when:
      event:
        - push
        - pull_request


#---

#kind: pipeline
#type: kubernetes
#name: default

#steps:
#  - name: terraform
#    image: hashicorp/terraform
#    environment:
#      AWS_ACCESS_KEY_ID:
#        from_secret: AWS_ACCESS_KEY_ID
#      AWS_SECRET_ACCESS_KEY:
#        from_secret: AWS_SECRET_ACCESS_KEY
#    commands:
#      - terraform init
#      - terraform plan
#      - terraform apply
#    when:
#      event:
#        - push
#        - pull_request
