kind: pipeline
type: kubernetes
name: default

steps:
  - name: terraform
    image: ciaranmcc/custom-terraform-awscli-image
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
#      - echo $AWS_ACCESS_KEY_ID
      - export AWS_ACCESS_KEY_ID="AKIA4EKE3O5JEYYCFWXJ"
      - export AWS_SECRET_ACCESS_KEY="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"
      - echo "Printing environment variables...."
      - aws_role_cred=$(aws sts assume-role --role-arn "arn:aws:iam::833904932690:role/DroneCI" --role-session-name drone-ci)
      - export AWS_ACCESS_KEY_ID=$(echo $aws_role_cred | jq .Credentials.AccessKeyId | xargs)
      - export AWS_SECRET_ACCESS_KEY=$(echo $aws_role_cred | jq .Credentials.SecretAccessKey | xargs)
      - export AWS_SESSION_TOKEN=$(echo $aws_role_cred | jq .Credentials.SessionToken |xargs)
      - terraform init
      - terraform plan
    when:
      event:
        - push
        - pull_request


