kind: pipeline
type: kubernetes
name: default

steps:
  - name: terraform
    image: hashicorp/terraform
    environment:
       TF_VAR_AWS_ACCESS_KEY_ID:
        from_secret: drone-aws-credentials
       TF_VAR_AWS_SECRET_ACCESS_KEY:
        from_secret: drone-aws-credentials
    commands:
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
    when:
      event:
        - push
        - pull_request


#---

#kind: pipeline
#type: kubernetes
#name: default

#steps:
#  - name: terraform
#    image: hashicorp/terraform
#    environment:
#      AWS_ACCESS_KEY_ID:
#        from_secret: AWS_ACCESS_KEY_ID
#      AWS_SECRET_ACCESS_KEY:
#        from_secret: AWS_SECRET_ACCESS_KEY
#    commands:
#      - terraform init
#      - terraform plan
#      - terraform apply
#    when:
#      event:
#        - push
#        - pull_request
